### ISSUE TITLE
该升级了，大佬

### ISSUE THREAD

**Issue by fengdoushi** [xuedingmiaojun/wxappUnpacker#13]
最新的版本解包不了了

**Comment by fengdoushi** [comment]
C:\Users\fengzi\Desktop\wxappUnpacker-master>node .\wuWxapkg.js  -d -f   C:\User
s\fengzi\Desktop\x\1.wxapkg
Unpack file C:\Users\fengzi\Desktop\x\1.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  2975
  dataLength:  781129
  lastMark: 0xed

File list info:
  fileCount:  60
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
deal config ok
deal js ok
deal html ok
deal css ok
splitJs: C:\Users\fengzi\Desktop\x\1\app-service.js
C:\Users\fengzi\Desktop\x\1 0081E1534FE949DF66E78954008B6CC4.js
C:\Users\fengzi\Desktop\x\1 0A44ADC34FE949DF6C22C5C4880B6CC4.js
C:\Users\fengzi\Desktop\x\1 0AB339224FE949DF6CD55125E56B6CC4.js
C:\Users\fengzi\Desktop\x\1 1D47B9604FE949DF7B21D16711AB6CC4.js
C:\Users\fengzi\Desktop\x\1 4C6659654FE949DF2A003162C95B6CC4.js
C:\Users\fengzi\Desktop\x\1 5F2019504FE949DF39467157B31B6CC4.js
C:\Users\fengzi\Desktop\x\1 64ACA1554FE949DF02CAC952522B6CC4.js
C:\Users\fengzi\Desktop\x\1 714FD1054FE949DF1729B9029C3B6CC4.js
C:\Users\fengzi\Desktop\x\1 82F1DA824FE949DFE497B285084B6CC4.js
C:\Users\fengzi\Desktop\x\1 8AC55E044FE949DFECA33603BE8B6CC4.js
C:\Users\fengzi\Desktop\x\1 914454404FE949DFF7223C477E2B6CC4.js
C:\Users\fengzi\Desktop\x\1 93BBF4B24FE949DFF5DD9CB5657B6CC4.js
C:\Users\fengzi\Desktop\x\1 app.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/action-sheet/action-sheet.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/gzh/gzh.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/login/login.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/poster/poster.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/index/index.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/task/task.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/tousu/tousu.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/detail/detail.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/jf-mall/jf-mall.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/invite/invite.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/invite/invitelist.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/info/info.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/record/record.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/show/show.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/record/record_pages.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/question/question.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/more/more.js
Splitting "C:\Users\fengzi\Desktop\x\1\app-service.js" done.
Decompile ./wei_idiom/component/action-sheet/action-sheet.wxml...
Decompile success!
Decompile ./wei_idiom/component/gzh/gzh.wxml...
Decompile success!
Decompile ./wei_idiom/component/login/login.wxml...
Decompile success!
Decompile ./wei_idiom/component/poster/poster.wxml...
Decompile success!
Decompile ./wei_idiom/pages/detail/detail.wxml...
Decompile success!
Decompile ./wei_idiom/pages/index/index.wxml...
Decompile success!
Decompile ./wei_idiom/pages/info/info.wxml...
Decompile success!
Decompile ./wei_idiom/pages/invite/invite.wxml...
Decompile success!
Decompile ./wei_idiom/pages/invite/invitelist.wxml...
Decompile success!
Decompile ./wei_idiom/pages/jf-mall/jf-mall.wxml...
Decompile success!
Decompile ./wei_idiom/pages/more/more.wxml...
Decompile success!
Decompile ./wei_idiom/pages/question/question.wxml...
Decompile success!
Decompile ./wei_idiom/pages/record/record.wxml...
Decompile success!
Decompile ./wei_idiom/pages/record/record_pages.wxml...
Decompile success!
Decompile ./wei_idiom/pages/show/show.wxml...
Decompile success!
Decompile ./wei_idiom/pages/task/task.wxml...
Decompile success!
Decompile ./wei_idiom/pages/tousu/tousu.wxml...
Decompile success!
Guess wxss(first turn)...
Import count info: {}
Guess wxss(first turn) done.
Generate wxss(second turn)...
Generate wxss(second turn) done.
Save wxss...
saveDir: C:\Users\fengzi\Desktop\x\1
Split and make up done.
Total use: 3028.124ms

C:\Users\fengzi\Desktop\wxappUnpacker-master>node .\wuConfig.js C:\Users\fengzi\
Desktop\x\1.wxapkg
undefined:1
�
^

SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\fengzi\Desktop\wxappUnpacker-master\wuConfig.js:30:22
    at C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:103:14
    at agent (C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:66:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_c
ontext.js:63:3)

C:\Users\fengzi\Desktop\wxappUnpacker-master>node .\wuJs.js C:\Users\fengzi\Desk
top\x\1.wxapkg
splitJs: C:\Users\fengzi\Desktop\x\1.wxapkg
vm.js:1
�


SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at VM.run (C:\Users\fengzi\Desktop\wxappUnpacker-master\node_modules\vm2\lib
\main.js:834:13)
    at C:\Users\fengzi\Desktop\wxappUnpacker-master\wuJs.js:48:12
    at C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:103:14
    at agent (C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:66:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_c
ontext.js:63:3)

C:\Users\fengzi\Desktop\wxappUnpacker-master>node .\wuWxml.js C:\Users\fengzi\De
sktop\x\1.wxapkg
Decompile ./wei_idiom/component/action-sheet/action-sheet.wxml...
Decompile success!
Decompile ./wei_idiom/component/gzh/gzh.wxml...
Decompile success!
Decompile ./wei_idiom/component/login/login.wxml...
Decompile success!
Decompile ./wei_idiom/component/poster/poster.wxml...
Decompile success!
Decompile ./wei_idiom/pages/detail/detail.wxml...
Decompile success!
Decompile ./wei_idiom/pages/index/index.wxml...
Decompile success!
Decompile ./wei_idiom/pages/info/info.wxml...
Decompile success!
Decompile ./wei_idiom/pages/invite/invite.wxml...
Decompile success!
Decompile ./wei_idiom/pages/invite/invitelist.wxml...
Decompile success!
Decompile ./wei_idiom/pages/jf-mall/jf-mall.wxml...
Decompile success!
Decompile ./wei_idiom/pages/more/more.wxml...
Decompile success!
Decompile ./wei_idiom/pages/question/question.wxml...
Decompile success!
Decompile ./wei_idiom/pages/record/record.wxml...
Decompile success!
Decompile ./wei_idiom/pages/record/record_pages.wxml...
Decompile success!
Decompile ./wei_idiom/pages/show/show.wxml...
Decompile success!
Decompile ./wei_idiom/pages/task/task.wxml...
Decompile success!
Decompile ./wei_idiom/pages/tousu/tousu.wxml...
Decompile success!
Total use: 550.592ms

C:\Users\fengzi\Desktop\wxappUnpacker-master>node .\wuWxss.js C:\Users\fengzi\De
sktop\x\1.wxapkg
C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:123
            if (err) throw Error("Scan dir error: " + err);
                     ^

Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'C:\Users\fengzi
\Desktop\x\1.wxapkg'
    at C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:123:28
    at agent (C:\Users\fengzi\Desktop\wxappUnpacker-master\wuLib.js:66:23)
    at FSReqCallback.oncomplete (fs.js:156:23)

C:\Users\fengzi\Desktop\wxappUnpacker-master>node .\wuWxapkg.js  -d -f   C:\User
s\fengzi\Desktop\x\1.wxapkg
Unpack file C:\Users\fengzi\Desktop\x\1.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  2975
  dataLength:  781129
  lastMark: 0xed

File list info:
  fileCount:  60
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
deal config ok
deal js ok
deal html ok
deal css ok
splitJs: C:\Users\fengzi\Desktop\x\1\app-service.js
C:\Users\fengzi\Desktop\x\1 0081E1534FE949DF66E78954008B6CC4.js
C:\Users\fengzi\Desktop\x\1 0A44ADC34FE949DF6C22C5C4880B6CC4.js
C:\Users\fengzi\Desktop\x\1 0AB339224FE949DF6CD55125E56B6CC4.js
C:\Users\fengzi\Desktop\x\1 1D47B9604FE949DF7B21D16711AB6CC4.js
C:\Users\fengzi\Desktop\x\1 4C6659654FE949DF2A003162C95B6CC4.js
C:\Users\fengzi\Desktop\x\1 5F2019504FE949DF39467157B31B6CC4.js
C:\Users\fengzi\Desktop\x\1 64ACA1554FE949DF02CAC952522B6CC4.js
C:\Users\fengzi\Desktop\x\1 714FD1054FE949DF1729B9029C3B6CC4.js
C:\Users\fengzi\Desktop\x\1 82F1DA824FE949DFE497B285084B6CC4.js
C:\Users\fengzi\Desktop\x\1 8AC55E044FE949DFECA33603BE8B6CC4.js
C:\Users\fengzi\Desktop\x\1 914454404FE949DFF7223C477E2B6CC4.js
C:\Users\fengzi\Desktop\x\1 93BBF4B24FE949DFF5DD9CB5657B6CC4.js
C:\Users\fengzi\Desktop\x\1 app.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/action-sheet/action-sheet.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/gzh/gzh.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/login/login.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/component/poster/poster.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/index/index.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/task/task.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/tousu/tousu.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/detail/detail.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/jf-mall/jf-mall.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/invite/invite.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/invite/invitelist.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/info/info.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/record/record.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/show/show.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/record/record_pages.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/question/question.js
C:\Users\fengzi\Desktop\x\1 wei_idiom/pages/more/more.js
Splitting "C:\Users\fengzi\Desktop\x\1\app-service.js" done.
Decompile ./wei_idiom/component/action-sheet/action-sheet.wxml...
Decompile success!
Decompile ./wei_idiom/component/gzh/gzh.wxml...
Decompile success!
Decompile ./wei_idiom/component/login/login.wxml...
Decompile success!
Decompile ./wei_idiom/component/poster/poster.wxml...
Decompile success!
Decompile ./wei_idiom/pages/detail/detail.wxml...
Decompile success!
Decompile ./wei_idiom/pages/index/index.wxml...
Decompile success!
Decompile ./wei_idiom/pages/info/info.wxml...
Decompile success!
Decompile ./wei_idiom/pages/invite/invite.wxml...
Decompile success!
Decompile ./wei_idiom/pages/invite/invitelist.wxml...
Decompile success!
Decompile ./wei_idiom/pages/jf-mall/jf-mall.wxml...
Decompile success!
Decompile ./wei_idiom/pages/more/more.wxml...
Decompile success!
Decompile ./wei_idiom/pages/question/question.wxml...
Decompile success!
Decompile ./wei_idiom/pages/record/record.wxml...
Decompile success!
Decompile ./wei_idiom/pages/record/record_pages.wxml...
Decompile success!
Decompile ./wei_idiom/pages/show/show.wxml...
Decompile success!
Decompile ./wei_idiom/pages/task/task.wxml...
Decompile success!
Decompile ./wei_idiom/pages/tousu/tousu.wxml...
Decompile success!
Guess wxss(first turn)...
Import count info: {}
Guess wxss(first turn) done.
Generate wxss(second turn)...
Generate wxss(second turn) done.
Save wxss...
saveDir: C:\Users\fengzi\Desktop\x\1
Split and make up done.
Total use: 3276.805ms

C:\Users\fengzi\Desktop\wxappUnpacker-master>

**Comment by xuedingmiaojun** [comment]
有新包吗 发来看看

**Comment by fengdoushi** [comment]
这个包..链接: https://pan.baidu.com/s/1KSSLttyrtvUqMSMqiLHfcw 提取码: rxvh 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Jerrodly** [comment]
发现主包可以解开，但是里面检查到关联的子包，都无法解析，解析出来的子包的wxml文件内容都是空的

**Comment by zy0228** [comment]
> @xuedingmiaojun 发现主包可以解开，但是里面检查到关联的子包，都无法解析，解析出来的子包的wxml文件内容都是空的

解决了吗现在

**Comment by hyq1860** [comment]
的确这个情况

**Comment by SunXinFei** [comment]
> 有新包吗 发来看看

确实 新包1.4M 解构出来的包才400kb  很多东西是空的

**Comment by tianbian224** [comment]
有其他的工具可以解包吗
