### ISSUE TITLE
function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]

### ISSUE THREAD

**Issue by bl382137136** [xuedingmiaojun/wxappUnpacker#21]
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
^^^^^^

SyntaxError: Illegal return statement
    at new Script (vm.js:83:7)
    at VM.run (C:\Users\DELL\node_modules\vm2\lib\main.js:834:13)
    at z (C:\Users\DELL\Desktop\wxappUnpacker-master\wuWxml.js:399:16)
    at z (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:280:21)
    at catchZGroup (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:16:2)
    at catchZ (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:21:33)
    at getZ (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:280:3)
    at wu.get.code (C:\Users\DELL\Desktop\wxappUnpacker-master\wuWxml.js:382:9)
    at ioLimit.runWithCb (C:\Users\DELL\Desktop\wxappUnpacker-master\wuLib.js:103:14)
    at agent (C:\Users\DELL\Desktop\wxappUnpacker-master\wuLib.js:66:23)

**Comment by newketom** [comment]
解决了吗

**Comment by Left-Hai** [comment]
+1

**Comment by cmhello88** [comment]
+1

**Comment by izuojian** [comment]
+1

**Comment by MrDon94** [comment]
+1

**Comment by xuedingmiaojun** [comment]
please contact to blogger

**Comment by xuedingmiaojun** [comment]
> return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
> ^^^^^^
> 
> SyntaxError: Illegal return statement
> at new Script (vm.js:83:7)
> at VM.run (C:\Users\DELL\node_modules\vm2\lib\main.js:834:13)
> at z (C:\Users\DELL\Desktop\wxappUnpacker-master\wuWxml.js:399:16)
> at z (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:280:21)
> at catchZGroup (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:16:2)
> at catchZ (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:21:33)
> at getZ (C:\Users\DELL\Desktop\wxappUnpacker-master\wuRestoreZ.js:280:3)
> at wu.get.code (C:\Users\DELL\Desktop\wxappUnpacker-master\wuWxml.js:382:9)
> at ioLimit.runWithCb (C:\Users\DELL\Desktop\wxappUnpacker-master\wuLib.js:103:14)
> at agent (C:\Users\DELL\Desktop\wxappUnpacker-master\wuLib.js:66:23)

把包发我看看吧

**Comment by sbigtree** [comment]
@xuedingmiaojun 解决了吗

**Comment by 781732825** [comment]
+1

**Comment by xuedingmiaojun** [comment]
> +1

https://www.bilibili.com/video/BV1Lv411a73w/

**Comment by zhongshuiping** [comment]
大佬 解决了？

**Comment by zhangdaren** [comment]
解决了吗？

**Comment by zhangdaren** [comment]
解决了吗？

**Comment by biggfish3147** [comment]
遇到相同的问题！没有找到解决方案。

定位到报错位置\node_modules\vm2\lib\main.js:932:13，vm.Script类的实例包含预编译脚本，构造方法参数scriptCode是要编译的JS代码，后一个参数是可选的配置对象。报错提示说要编译的JS代码出现语法错误。如果分析不错，说明脚本没有适配这种异常类型。

script = new vm.Script(scriptCode, {
				filename: useFileName,
				displayErrors: false,
				importModuleDynamically
			});

PS 另一种十分相似的报错可以通过更换脚本解决，但仅适用部分小程序。https://blog.csdn.net/wq57885/article/details/101113017

**Comment by xuedingmiaojun** [comment]
> 大佬 解决了？

已解决

**Comment by zhangdaren** [comment]
> > 大佬 解决了？
> 
> 已解决

大佬怎么解决的？

**Comment by zmqcherish** [comment]
有解了吗，有的包能成功解，有的报错

**Comment by scrapstation** [comment]
> > > 大佬 解决了？
> > 
> > 
> > 已解决
> 
> 怎么解决啊 大佬

大佬披星戴月搞定的，可能免费告诉你吗？

**Comment by Haojinlong555** [comment]
大佬怎么解决的啊
