### ISSUE TITLE
抛出异常 Error: ENOTDIR: not a directory, scandir '/Users/fanybo_m/Desktop/wx/zhu/WAAutoService.js'

### ISSUE THREAD

**Issue by kerncoola** [xuedingmiaojun/wxappUnpacker#22]
Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  498
  dataLength:  11218321
  lastMark: 0xed

File list info:
  fileCount:  18
Saving files...
Unpack done.
now dir: /Users/fanybo_m/Desktop/wx/zhu
param of mainDir: /Users/fanybo_m/Desktop/wx/fen
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir '/Users/fanybo_m/Desktop/wx/zhu/WAAutoService.js'
    at Object.readdirSync (fs.js:1021:3)
    at findDir (/Users/fanybo_m/Desktop/wx/wuWxapkg.js:154:36)
    at findDir (/Users/fanybo_m/Desktop/wx/wuWxapkg.js:165:29)
    at Array.packDone (/Users/fanybo_m/Desktop/wx/wuWxapkg.js:171:17)
    at CntEvent.decount (/Users/fanybo_m/Desktop/wx/wuLib.js:22:54)
    at /Users/fanybo_m/Desktop/wx/wuLib.js:95:17
    at agent (/Users/fanybo_m/Desktop/wx/wuLib.js:66:23)
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/Users/fanybo_m/Desktop/wx/zhu/WAAutoService.js'
}

**Comment by xuedingmiaojun** [comment]
> Header info:
> firstMark: 0xbe
> unknownInfo: 0
> infoListLength: 498
> dataLength: 11218321
> lastMark: 0xed
> 
> File list info:
> fileCount: 18
> Saving files...
> Unpack done.
> now dir: /Users/fanybo_m/Desktop/wx/zhu
> param of mainDir: /Users/fanybo_m/Desktop/wx/fen
> internal/fs/utils.js:307
> throw err;
> ^
> 
> Error: ENOTDIR: not a directory, scandir '/Users/fanybo_m/Desktop/wx/zhu/WAAutoService.js'
> at Object.readdirSync (fs.js:1021:3)
> at findDir (/Users/fanybo_m/Desktop/wx/wuWxapkg.js:154:36)
> at findDir (/Users/fanybo_m/Desktop/wx/wuWxapkg.js:165:29)
> at Array.packDone (/Users/fanybo_m/Desktop/wx/wuWxapkg.js:171:17)
> at CntEvent.decount (/Users/fanybo_m/Desktop/wx/wuLib.js:22:54)
> at /Users/fanybo_m/Desktop/wx/wuLib.js:95:17
> at agent (/Users/fanybo_m/Desktop/wx/wuLib.js:66:23)
> at FSReqCallback.oncomplete (fs.js:171:23) {
> errno: -20,
> syscall: 'scandir',
> code: 'ENOTDIR',
> path: '/Users/fanybo_m/Desktop/wx/zhu/WAAutoService.js'
> }

包错了

**Comment by Upsetin** [comment]
请问解决了吗，我也遇到了类似问题

**Comment by xiaoas** [comment]
同遇到问题
```
$ ./bingo.sh _1801643844_52.wxapkg -s=_-462690073_52
node /mnt/d/wxappUnpacker/wuWxapkg.js
Unpack file _1801643844_52.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  28
  dataLength:  4795940
  lastMark: 0xed

File list info:
  fileCount:  1
Saving files...
Unpack done.
now dir: /mnt/d/wxappUnpacker/_1801643844_52
param of mainDir: _-462690073_52
fs.js:114
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir '/mnt/d/wxappUnpacker/_1801643844_52/sub/game.js'
    at Object.readdirSync (fs.js:790:3)
    at findDir (/mnt/d/wxappUnpacker/wuWxapkg.js:154:36)
    at findDir (/mnt/d/wxappUnpacker/wuWxapkg.js:165:29)
    at findDir (/mnt/d/wxappUnpacker/wuWxapkg.js:165:29)
    at Array.packDone (/mnt/d/wxappUnpacker/wuWxapkg.js:171:17)
    at CntEvent.decount (/mnt/d/wxappUnpacker/wuLib.js:22:54)
    at ioLimit.runWithCb.err (/mnt/d/wxappUnpacker/wuLib.js:95:17)
    at agent (/mnt/d/wxappUnpacker/wuLib.js:66:23)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```
这个叫sub的包 导入不能
