### ISSUE TITLE
无法生成 page-frame.html 文件，报错SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by yydmss** [xuedingmiaojun/wxappUnpacker#24]
程序执行命令(可选): node wuWxapkg.js testpkg/0.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
SyntaxError: Unexpected identifier
    at new Script (vm.js:88:7)
    at VM.run (E:\node\wxappUnpacker2021\node_modules\vm2\lib\main.js:834:13)
    at E:\node\wxappUnpacker2021\wuConfig.js:91:21
    at E:\node\wxappUnpacker2021\wuLib.js:103:14
    at agent (E:\node\wxappUnpacker2021\wuLib.js:66:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
链接：https://share.weiyun.com/cVUKDKaz 密码：dy28vt

其他附加内容:
无法生成出 page-frame.html 文件，导致后续无法还原主包的html。依赖全部安装了，手动解包也无法生成， 麻烦了~辛苦您查看下

**Comment by pygroos** [comment]
同样的问题。麻烦了~辛苦您查看下
[adui.wxapkg.zip](https://github.com/xuedingmiaojun/wxappUnpacker/files/7128233/adui.wxapkg.zip)
