### ISSUE TITLE
ReferenceError [Error]: window is not defined

### ISSUE THREAD

**Issue by moming159** [xuedingmiaojun/wxappUnpacker#28]
wxappUnpacker-master/node_modules/vm2/lib/main.js:845
				throw this._internal.Decontextify.value(e);
				^
ReferenceError [Error]: window is not defined
    at setCssToHead_wxfa43a4a7041a84de (vm.js:31:25)
    at vm.js:82:1
    at Script.runInContext (node:vm:141:12)
    at VM.run (/.../wxappUnpacker-master/node_modules/vm2/lib/main.js:843:53)
    at /.../wxappUnpacker-master/wuWxss.js:267:42
    at /.../wechat/wxappUnpacker-master/wuLib.js:103:14
    at agent (/.../wxappUnpacker-master/wuLib.js:66:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)

**Comment by xuedingmiaojun** [comment]
> wxappUnpacker-master/node_modules/vm2/lib/main.js:845
> throw this._internal.Decontextify.value(e);
> ^
> ReferenceError [Error]: window is not defined
> at setCssToHead_wxfa43a4a7041a84de (vm.js:31:25)
> at vm.js:82:1
> at Script.runInContext (node:vm:141:12)
> at VM.run (/.../wxappUnpacker-master/node_modules/vm2/lib/main.js:843:53)
> at /.../wxappUnpacker-master/wuWxss.js:267:42
> at /.../wechat/wxappUnpacker-master/wuLib.js:103:14
> at agent (/.../wxappUnpacker-master/wuLib.js:66:23)
> at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)

私聊解决

**Comment by Invincibl-e** [comment]
@xuedingmiaojun 怎么联系你

**Comment by xuedingmiaojun** [comment]
> @xuedingmiaojun 怎么联系你

博客有wx

**Comment by liudonghua123** [comment]
我也是相同问题，首先我通过`UnpackMiniApp.exe`解密wxapkg，然后`bingo.bat decrypted.wxapkg`，就提示这个错误了。
[UnpackMiniApp.zip](https://github.com/xuedingmiaojun/wxappUnpacker/files/7140514/UnpackMiniApp.zip)
