### ISSUE TITLE
反编译报错：Unexpected end of input

### ISSUE THREAD

**Issue by ekko-zhao** [xuedingmiaojun/wxappUnpacker#30]
反编译小程序时候报错， 麻烦帮忙看看是什么原因，谢谢。

程序执行命令(可选):

./bingo.sh 6152/1.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
SyntaxError: Unexpected end of input
    at new Script (node:vm:99:7)
    at VM.run (/Users/ekko/Downloads/wxappUnpacker/node_modules/vm2/lib/main.js:878:13)
    at /Users/ekko/Downloads/wxappUnpacker/wuWxss.js:243:27
    at /Users/ekko/Downloads/wxappUnpacker/wuLib.js:95:14
    at agent (/Users/ekko/Downloads/wxappUnpacker/wuLib.js:64:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:69:3)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
[归档.zip](https://github.com/xuedingmiaojun/wxappUnpacker/files/6656906/default.zip)

其他附加内容:
![image](https://user-images.githubusercontent.com/26781518/122082957-05269280-ce33-11eb-97d1-d2af1a7a0b44.png)

**Comment by Chiana1725** [comment]
![image](https://user-images.githubusercontent.com/36362974/158123823-1688c477-345e-4fd2-82c9-d0129a77894b.png)

**Comment by sccscc321** [comment]
![QQ截图20221106210104](https://user-images.githubusercontent.com/77774767/200172211-1e8f88e3-48d2-4469-903a-01edc4a1fcc8.jpg)
又出现这个
