### ISSUE TITLE
解析主包出现错误

### ISSUE THREAD

**Issue by lijintao81** [xuedingmiaojun/wxappUnpacker#32]
发表 Issue 前请仔细阅读以下内容：

1. 如果你是要反馈 bug, 请按以下`模板`书写 Issue;
2. 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题;
3. 遇到包依赖问题，请联系对应项目;
4. 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理;
5. 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理;
6. 直接分包和直接处理含插件的包两个功能暂不支持, 请勿重复发表 Issue, 新样例可在已存在的 Issue 下提出;
7. 请不要在其他 Issue 下发表与该 Issue 无关的回复, 否则将有可能被删除。

模板内容如下：

程序执行命令(可选):
./bingo.sh ******/_675315740_294.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

SyntaxError: Illegal return statement
    at new Script (vm.js:101:7)
    at VM.run (*****/wxappUnpacker-xuedingmiaojun/node_modules/vm2/lib/main.js:878:13)
    at /*****/wxappUnpacker-xuedingmiaojun/wuWxml.js:399:16
    at /*****/wxappUnpacker-xuedingmiaojun/wuRestoreZ.js:280:21
    at catchZGroup (/*****/wxappUnpacker-xuedingmiaojun/wuRestoreZ.js:16:2)
    at catchZ (/*****/wxappUnpacker-xuedingmiaojun/wuRestoreZ.js:21:33)
    at getZ (/*****/wxappUnpacker-xuedingmiaojun/wuRestoreZ.js:280:3)
    at /*****/wxappUnpacker-xuedingmiaojun/wuWxml.js:382:9
    at /*****/wxappUnpacker-xuedingmiaojun/wuLib.js:103:14
    at agent (/*****/wxappUnpacker-xuedingmiaojun/wuLib.js:66:23)

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
[qcs.zip](https://github.com/xuedingmiaojun/wxappUnpacker/files/7030876/qcs.zip)

其他附加内容:
解析子包时，也会抛出问题：
执行命令：./bingo.sh -s=/****/_675315740_294 /****/_1564529943_294.wxapkg
抛出问题：
node /*****/wxappUnpacker-xuedingmiaojun/wuWxapkg.js
Unpack file /*****/_1564529943_294.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  11693
  dataLength:  1332150
  lastMark: 0xed

File list info:
  fileCount:  213
Saving files...
Unpack done.
now dir: /*****/_1564529943_294
param of mainDir: /*****/_675315740_294
sub package word dir: /*****/_1564529943_294/pages/member
real mainDir: /*****/_675315740_294
Split app-service.js and make up configs & wxss & wxml & wxs...
deal js ok
deal sub html ok
splitJs: /*****/_1564529943_294/pages/member/app-service.js
/*****/_675315740_294 pages/member/home/address.js
/*****/wxappUnpacker-xuedingmiaojun/node_modules/vm2/lib/main.js:890
				throw this._internal.Decontextify.value(e);
				^
ReferenceError [Error]: __g is not defined
    at vm.js:61:3
    at Script.runInContext (vm.js:143:18)
    at VM.run (/*****/wxappUnpacker-xuedingmiaojun/node_modules/vm2/lib/main.js:888:53)
    at /*****/wxappUnpacker-xuedingmiaojun/wuJs.js:48:12
    at /*****/wxappUnpacker-xuedingmiaojun/wuLib.js:103:14
    at agent (/*****/wxappUnpacker-xuedingmiaojun/wuLib.js:66:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

**Comment by xuedingmiaojun** [comment]
![image](https://user-images.githubusercontent.com/4709073/135200565-9db5abdf-9ba0-4e85-8c4d-3e93d1cc81af.png)
接口报错
