### ISSUE TITLE
Error: ENOTDIR: not a directory, scandir '/Users/xxx/Desktop/xcx_p/_1123949441_593/WAAutoService.js'

### ISSUE THREAD

**Issue by chengyuwen** [xuedingmiaojun/wxappUnpacker#35]
反编译：分包合到主包报错
报错信息：
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir '/Users/xxx/Desktop/xcx_p/_1123949441_593/WAAutoService.js'
    at Object.readdirSync (node:fs:1390:3)
    at findDir (/Users/xxx/Downloads/wxappUnpacker-master/wuWxapkg.js:154:36)
    at findDir (/Users/xxx/Downloads/wxappUnpacker-master/wuWxapkg.js:165:29)
    at Array.packDone (/Users/xxx/Downloads/wxappUnpacker-master/wuWxapkg.js:171:17)
    at CntEvent.decount (/Users/xxx/Downloads/wxappUnpacker-master/wuLib.js:22:54)
    at /Users/xxx/Downloads/wxappUnpacker-master/wuLib.js:95:17
    at agent (/Users/xxx/Downloads/wxappUnpacker-master/wuLib.js:66:23)
    at FSReqCallback.oncomplete (node:fs:188:23) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/Users/xxx/Desktop/xcx_p/_1123949441_593/WAAutoService.js'
}

**Comment by kenti-lan** [comment]
我也遇到同样的错误

**Comment by qiuluo-oss** [comment]
@kenti-lan @chengyuwen 两位大佬，问题处理好了吗？我也遇到这样的问题

**Comment by cheng1107** [comment]
我也遇到同样的问题，大佬解决了吗

**Comment by zhqpower** [comment]
有大佬解决吗，遇到同样的问题

**Comment by zhqpower** [comment]
> 反编译：分包合到主包报错 报错信息： node:internal/fs/utils:344 throw err; ^
> 
> Error: ENOTDIR: not a directory, scandir '/Users/xxx/Desktop/xcx_p/_1123949441_593/WAAutoService.js' at Object.readdirSync (node:fs:1390:3) at findDir (/Users/xxx/Downloads/wxappUnpacker-master/wuWxapkg.js:154:36) at findDir (/Users/xxx/Downloads/wxappUnpacker-master/wuWxapkg.js:165:29) at Array.packDone (/Users/xxx/Downloads/wxappUnpacker-master/wuWxapkg.js:171:17) at CntEvent.decount (/Users/xxx/Downloads/wxappUnpacker-master/wuLib.js:22:54) at /Users/xxx/Downloads/wxappUnpacker-master/wuLib.js:95:17 at agent (/Users/xxx/Downloads/wxappUnpacker-master/wuLib.js:66:23) at FSReqCallback.oncomplete (node:fs:188:23) { errno: -20, syscall: 'scandir', code: 'ENOTDIR', path: '/Users/xxx/Desktop/xcx_p/_1123949441_593/WAAutoService.js' }
@stathamcheng  解决了吗
