### ISSUE TITLE
 vm.compileFunction is not a function

### ISSUE THREAD

**Issue by LostKe** [xuedingmiaojun/wxappUnpacker#36]
```
D:\ntc-git-work\wxappUnpacker\node_modules\_vm2@3.9.5@vm2\lib\main.js:550
        vm.compileFunction(code, params);
           ^

TypeError: vm.compileFunction is not a function
    at tryCompile (D:\ntc-git-work\wxappUnpacker\node_modules\_vm2@3.9.5@vm2\lib\main.js:550:5)
    at VM.<anonymous> (D:\ntc-git-work\wxappUnpacker\node_modules\_vm2@3.9.5@vm2\lib\main.js:580:5)
    at VM.run (D:\ntc-git-work\wxappUnpacker\node_modules\_vm2@3.9.5@vm2\lib\main.js:920:23)
    at wu.get.code (D:\ntc-git-work\wxappUnpacker\wuJs.js:48:12)
    at ioLimit.runWithCb (D:\ntc-git-work\wxappUnpacker\wuLib.js:103:14)
    at agent (D:\ntc-git-work\wxappUnpacker\wuLib.js:66:23)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by qqizai** [comment]
同问，这个是如何解决这个问题？
