### ISSUE TITLE
Unexpected token '}'

### ISSUE THREAD

**Issue by raidtest** [xuedingmiaojun/wxappUnpacker#43]
vm.js:2651
}
^

SyntaxError: Unexpected token '}'
    at makeNiceSyntaxError (D:\src\github\wxappUnpacker\node_modules\vm2\lib\transformer.js:41:16)
    at transformer (D:\src\github\wxappUnpacker\node_modules\vm2\lib\transformer.js:84:8)
    at VM.run (D:\src\github\wxappUnpacker\node_modules\vm2\lib\vm.js:491:16)
    at D:\src\github\wxappUnpacker\wuWxml.js:399:16
    at D:\src\github\wxappUnpacker\wuRestoreZ.js:280:21
    at catchZGroup (D:\src\github\wxappUnpacker\wuRestoreZ.js:16:2)
    at catchZ (D:\src\github\wxappUnpacker\wuRestoreZ.js:21:33)
    at getZ (D:\src\github\wxappUnpacker\wuRestoreZ.js:280:3)
    at D:\src\github\wxappUnpacker\wuWxml.js:382:9
    at D:\src\github\wxappUnpacker\wuLib.js:103:14

goto:eof

**Comment by sccscc321** [comment]
+1

**Comment by cheng1107** [comment]
你好，我这也是同样的报错，请问解决了吗？

**Comment by sccscc321** [comment]
用win7 系统&nbsp; node用低版本 不超过14
&nbsp;

***@***.***，感谢您的谅解，现在新闻网祝您生活、工作愉快！顺祝开心快乐每一天！


&nbsp;

**Comment by KrystianLi** [comment]
> 

我是用win7 node13.12.0 依旧报错
vm.js:51
}
^

SyntaxError: Unexpected token '}'

能否详细提供你所使用的环境

**Comment by goccc** [comment]
请问有人解决了吗。

**Comment by caixi53880** [comment]
一样的问题，这是几年前开发的，已经不适配了
