### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by const-Ly** [xuedingmiaojun/wxappUnpacker#5]
```
SyntaxError: Unexpected end of input
[90m    at new Script (vm.js:86:7)[39m
    at VM.run (C:\Users\Administrator\Desktop\wxappUnpacke\wxappUnpacker-master\node_modules\[4mvm2
[24m\lib\main.js:834:13)
    at C:\Users\Administrator\Desktop\wxappUnpacke\wxappUnpacker-master\wuWxss.js:243:27
    at C:\Users\Administrator\Desktop\wxappUnpacke\wxappUnpacker-master\wuLib.js:95:14
    at agent (C:\Users\Administrator\Desktop\wxappUnpacke\wxappUnpacker-master\wuLib.js:64:23)
[90m    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
[39m
```

**Comment by GurglingY** [comment]
同 求解决办法

**Comment by 836257514** [comment]
Same question

**Comment by xuedingmiaojun** [comment]
有包吗 发来看下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "836257514"<notifications@github.com&gt;; 
发送时间: 2021年3月5日(星期五) 下午2:22
收件人: "xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [xuedingmiaojun/wxappUnpacker] SyntaxError: Unexpected end of input (#5)





 
Same question
 
&mdash;
